const form=document.querySelector('#release-form'), folderInput=document.querySelector('#release-folder'), trackList=document.querySelector('#track-list'), folderStatus=document.querySelector('#folder-status'), researchStatus=document.querySelector('#research-status'), researchResults=document.querySelector('#research-results');
const trackFields=['trackTitle','songwriters','producers','pLine','cLine','isrc']; let release={tracks:[],artwork:null,selected:0};
const RESEARCH_API='https://release-pilot-research.uwaandfriends-production.workers.dev/research';
const DRAFT_KEY='release-pilot-draft-v3';
const HELPER_API='http://127.0.0.1:47831';
const esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function parse(name){const s=name.replace(/\.[^.]+$/,'').replace(/^\d+[ ._-]+/,'').replace(/_/g,' ').trim(),p=s.split(/\s+-\s+/);return p.length>1?{title:p.slice(0,-1).join(' - '),artist:p.at(-1)}:{title:s,artist:''}}
function cur(){return release.tracks[release.selected]} function save(){if(typeof wizardStep!=='undefined'&&wizardStep===3)return;if(!cur())return;trackFields.forEach(k=>cur()[k]=form.elements[k].value);cur().artist=form.elements.primaryArtist.value||cur().artist}
function renderSongMetadata(){const box=document.querySelector('#song-metadata');if(!box)return;box.innerHTML=release.tracks.map((t,i)=>`<div class="song-row"><b>${i+1}</b><input data-song="${i}" data-key="trackTitle" value="${esc(t.trackTitle)}" aria-label="Judul lagu ${i+1}" /><input data-song="${i}" data-key="songwriters" value="${esc(t.songwriters)}" placeholder="Penulis lagu" aria-label="Penulis lagu ${i+1}" /><input data-song="${i}" data-key="isrc" value="${esc(t.isrc)}" placeholder="ISRC (opsional)" aria-label="ISRC ${i+1}" /></div>`).join('');box.querySelectorAll('[data-song]').forEach(input=>input.oninput=()=>{release.tracks[+input.dataset.song][input.dataset.key]=input.value;render();update()})}
function render(){trackList.innerHTML=release.tracks.map((t,i)=>`<button type="button" class="track ${i===release.selected?'selected':''} ${t.researched?'researched':''}" data-track="${i}"><span>${esc(t.trackTitle)}</span><small>${t.songwriters?`Pencipta: ${esc(t.songwriters)}`:'Pencipta: perlu riset'}</small><em>${t.researched?'✓ Diriset':'Riset'}</em></button>`).join('');trackList.hidden=!release.tracks.length;trackList.querySelectorAll('[data-track]').forEach(b=>b.onclick=()=>{save();release.selected=+b.dataset.track;load()})}
function load(){const t=cur();if(!t)return;trackFields.forEach(k=>form.elements[k].value=t[k]||'');if(!form.elements.primaryArtist.value&&t.artist)form.elements.primaryArtist.value=t.artist;if(!form.elements.title.value)form.elements.title.value=t.trackTitle;render();renderSongMetadata();update()}
function importFolder(){const fs=[...folderInput.files].filter(f=>f.webkitRelativePath.split('/').length===2),aud=fs.filter(f=>/\.(wav|flac|mp3|m4a)$/i.test(f.name)),imgs=fs.filter(f=>/\.(jpg|jpeg|png)$/i.test(f.name));release.artwork=imgs.find(f=>/^(cover|artwork|front)/i.test(f.name))||imgs[0];const y=new Date().getFullYear(),owner=form.elements.primaryArtist.value;release.tracks=aud.map(file=>{const p=parse(file.name),o=owner||p.artist;return{file,artist:p.artist,trackTitle:p.title,songwriters:'',producers:'',pLine:o?`℗ ${y} ${o}`:'',cLine:o?`© ${y} ${o}`:'',isrc:'',researched:false}});release.selected=0;folderStatus.textContent=aud.length?`${aud.length} lagu ditemukan di folder utama${release.artwork?` · cover: ${release.artwork.name}`:''}. Subfolder diabaikan.`:'Tidak ada audio di folder utama.';load()}
function candidateMarkup(result,trackIndex){const usable=result.candidates.filter(c=>c.songwriter);const sources=result.candidates.slice(0,5);return `<section class="research-track"><h3>${esc(result.title)}</h3>${usable.length?usable.map((c,i)=>`<article class="candidate"><div><strong>${esc(c.title)}</strong><p>Pencipta: ${esc(c.songwriter)}</p><a href="${esc(c.sourceUrl)}" target="_blank" rel="noreferrer">${esc(c.source)} · ${esc(c.sourceTitle)}</a></div><button type="button" data-pick="${trackIndex}" data-candidate="${i}">Pilih</button></article>`).join(''):`<p class="no-match">Belum ada nama pencipta yang dapat dibaca otomatis. Periksa sumber di bawah atau pilih status yang sesuai.</p>`}<div class="source-list">${sources.map(c=>`<a href="${esc(c.sourceUrl)}" target="_blank" rel="noreferrer">${esc(c.source)} · ${esc(c.sourceTitle)}</a>`).join('')}<a href="${esc(result.googleUrl)}" target="_blank" rel="noreferrer">Lihat hasil lengkap di Google</a></div><div class="fallback-actions"><button type="button" data-fallback="${trackIndex}" data-writer="Anonim">Tidak ditemukan — Anonim</button><button type="button" data-fallback="${trackIndex}" data-writer="Publik Domain">Publik domain</button></div></section>`}
function bindCandidates(results){researchResults.querySelectorAll('[data-pick]').forEach(button=>button.onclick=()=>{const item=results.find(r=>r.trackIndex===+button.dataset.pick),candidate=item?.candidates.filter(c=>c.songwriter)[+button.dataset.candidate];if(!item||!candidate)return;const track=release.tracks[item.trackIndex];track.trackTitle=candidate.title;track.songwriters=candidate.songwriter;track.researched=true;release.selected=item.trackIndex;render();load();researchStatus.textContent=`${track.trackTitle} diperbarui. Verifikasi lagi melalui tautan sumber sebelum distribusi.`});researchResults.querySelectorAll('[data-fallback]').forEach(button=>button.onclick=()=>{const track=release.tracks[+button.dataset.fallback];track.songwriters=button.dataset.writer;track.researched=true;release.selected=+button.dataset.fallback;render();load();researchStatus.textContent=`${track.trackTitle}: pencipta diisi ${track.songwriters}.`})}
async function research(all){save();const indexed=(all?release.tracks.map((track,trackIndex)=>({track,trackIndex})):[{track:cur(),trackIndex:release.selected}]).filter(x=>x.track);if(!indexed.length){researchStatus.textContent='Pilih folder terlebih dahulu.';return}const brief=form.elements.researchBrief.value.trim(),buttons=[document.querySelector('#research'),document.querySelector('#research-all')];buttons.forEach(b=>b.disabled=true);researchStatus.textContent=`Mencari referensi untuk ${indexed.length} lagu…`;researchResults.hidden=true;try{const results=[];for(let start=0;start<indexed.length;start+=3){const batch=indexed.slice(start,start+3);const found=await Promise.all(batch.map(async({track,trackIndex})=>{const response=await fetch(RESEARCH_API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:track.trackTitle,brief})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Riset gagal');return{...data,trackIndex}}));results.push(...found);researchStatus.textContent=`Riset ${Math.min(start+3,indexed.length)} dari ${indexed.length} lagu selesai…`}researchResults.innerHTML=results.map(r=>candidateMarkup(r,r.trackIndex)).join('');researchResults.hidden=false;bindCandidates(results);researchStatus.textContent=`Ditemukan referensi untuk ${results.length} lagu. Pilih kandidat pencipta lalu cek sumbernya.`}catch(error){researchStatus.textContent=`Riset belum berhasil: ${error.message}. Coba lagi beberapa saat.`}finally{buttons.forEach(b=>b.disabled=false)}}
function copyCommon(){save();const s=cur();if(!s)return;release.tracks.forEach(t=>{t.artist=form.elements.primaryArtist.value||t.artist;t.producers=s.producers;t.pLine=s.pLine;t.cLine=s.cLine});render();researchStatus.textContent='Artis, produser, dan baris hak disalin ke semua lagu.'}
function update(){const t=cur(),asset=t?.file||document.querySelector('#audio').files[0],art=release.artwork||document.querySelector('#artwork').files[0],assetName=asset?.name||t?.audioFile,artName=art?.name||release.artworkName;document.querySelector('#asset-status').textContent=[assetName&&`Audio: ${assetName}`,artName&&`Cover: ${artName}`].filter(Boolean).join(' · ')||'Belum ada aset dipilih.';document.querySelector('#readiness').textContent=release.tracks.some(t=>!t.songwriters)?'Belum siap: pencipta lagu pada semua track.':'Periksa kembali sebelum ekspor.'}
form.addEventListener('input',update);folderInput.onchange=importFolder;document.querySelector('#research').onclick=()=>research(false);document.querySelector('#research-all').onclick=()=>research(true);

function formSnapshot(){const values={};[...form.elements].forEach(field=>{if(!field.name||field.type==='file'||['trackTitle','songwriters','isrc'].includes(field.name))return;if(field.type==='checkbox')values[field.name]=field.checked;else if(field.type!=='radio'||field.checked)values[field.name]=field.value});return values}
function applyFormSnapshot(values={}){[...form.elements].forEach(field=>{if(!field.name||!(field.name in values)||field.type==='file')return;if(field.type==='checkbox')field.checked=Boolean(values[field.name]);else if(field.type==='radio')field.checked=field.value===values[field.name];else field.value=values[field.name]})}
function draftPayload(){save();return{version:3,savedAt:new Date().toISOString(),step:wizardStep,maxStep:maxWizardStep,selected:release.selected,form:formSnapshot(),artworkName:release.artwork?.name||release.artworkName||'',tracks:release.tracks.map(({file,...track})=>({...track,audioFile:file?.name||track.audioFile||''}))}}
function setDraftStatus(message,error=false){const el=document.querySelector('#draft-status');el.textContent=message;el.style.color=error?'#ff9eaa':'#91d8b2'}
function saveDraft(showMessage=true){const draft=draftPayload();localStorage.setItem(DRAFT_KEY,JSON.stringify(draft));if(showMessage)setDraftStatus(`Draft tersimpan lokal · ${new Date(draft.savedAt).toLocaleString('id-ID')}`);return draft}
function restoreDraft(){let draft;try{draft=JSON.parse(localStorage.getItem(DRAFT_KEY)||localStorage.getItem('release-pilot-draft-v2')||'null')}catch{return}if(!draft?.tracks?.length)return;release.tracks=draft.tracks.map(track=>({...track,file:null}));release.selected=Math.min(Number(draft.selected)||0,release.tracks.length-1);release.artworkName=draft.artworkName||'';applyFormSnapshot(draft.form);maxWizardStep=Math.max(1,Math.min(4,Number(draft.maxStep)||1));folderStatus.textContent=`Draft dipulihkan: ${release.tracks.length} lagu. Pilih folder yang sama lagi untuk menyambungkan file audio.`;load();showWizard(Math.max(1,Math.min(maxWizardStep,Number(draft.step)||1)));setDraftStatus('Draft lokal dipulihkan. Audio dan cover perlu dipilih kembali demi keamanan browser.')}
function exportPackage(){const draft=saveDraft(false);if(!release.tracks.length){setDraftStatus('Belum ada lagu untuk diekspor.',true);showWizard(1);return}if(!form.elements.original.checked){setDraftStatus('Centang konfirmasi hak distribusi sebelum melanjutkan.',true);return}const missing=release.tracks.filter(track=>!track.trackTitle||!track.songwriters);if(missing.length){setDraftStatus(`${missing.length} lagu belum memiliki judul atau pencipta. Lengkapi dahulu.`,true);showWizard(3);return}const payload={format:'hicca-amuse-release-package',version:3,exportedAt:new Date().toISOString(),release:draft.form,artworkFile:draft.artworkName,tracks:draft.tracks};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=Object.assign(document.createElement('a'),{href:url,download:'amuse-release-package.json'});link.click();setTimeout(()=>URL.revokeObjectURL(url),1500);setDraftStatus('Paket metadata berhasil diunduh.')}
function helperPayload(){const draft=saveDraft(false);return{format:'hicca-amuse-release-package',version:3,release:draft.form,artworkFile:draft.artworkName,tracks:draft.tracks}}
function validateUpload(){if(!release.tracks.length){setDraftStatus('Belum ada lagu untuk diunggah.',true);showWizard(1);return false}if(!form.elements.original.checked){setDraftStatus('Centang konfirmasi hak distribusi sebelum melanjutkan.',true);return false}const missing=release.tracks.filter(track=>!track.trackTitle||!track.songwriters||!track.audioFile&&!track.file);if(missing.length){setDraftStatus(`${missing.length} lagu belum lengkap atau belum tersambung ke audio.`,true);showWizard(3);return false}return true}
function showHelper(state,message){const el=document.querySelector('#helper-status'),cont=document.querySelector('#helper-continue');el.textContent=message||state;el.className=`helper-state ${state==='idle'||state==='review'?'ready':state==='error'?'error':''}`;cont.hidden=state!=='needs_login'}
async function helperRequest(path,options={}){const request=fetch(`${HELPER_API}${path}`,{...options,headers:{'content-type':'application/json',...(options.headers||{})}});const timeout=new Promise((_,reject)=>setTimeout(()=>reject(new Error('Helper tidak dapat dijangkau dari browser ini.')),3500));const response=await Promise.race([request,timeout]);const data=await response.json();if(!response.ok)throw new Error(data.error||'Helper gagal merespons');return data}
async function checkHelper(){try{const data=await helperRequest('/health');showHelper(data.job.state,data.job.message);return true}catch{showHelper('error','Helper tidak terhubung. Jalankan helper dan buka Release Pilot di Google Chrome lokal.');return false}}
let helperPoll;
function pollHelper(){clearInterval(helperPoll);helperPoll=setInterval(async()=>{try{const state=await helperRequest('/status');showHelper(state.state,state.message);if(['review','error'].includes(state.state))clearInterval(helperPoll)}catch{showHelper('error','Koneksi helper terputus.')}} ,1400)}
async function startHelper(){if(!validateUpload())return;const button=document.querySelector('#helper-upload');button.disabled=true;try{if(!await checkHelper())throw new Error('Aktifkan Hicca Upload Helper terlebih dahulu.');const state=await helperRequest('/prepare',{method:'POST',body:JSON.stringify(helperPayload())});showHelper(state.state,state.message);setDraftStatus('Helper dimulai. Pilih folder rilis pada dialog macOS.');pollHelper()}catch(error){setDraftStatus(error.message,true)}finally{button.disabled=false}}
async function continueHelper(){try{const state=await helperRequest('/continue',{method:'POST',body:'{}'});showHelper(state.state,state.message);pollHelper()}catch(error){setDraftStatus(error.message,true)}}
document.querySelector('#save').onclick=()=>saveDraft(true);
document.querySelector('#export').onclick=exportPackage;
document.querySelector('#helper-upload').onclick=startHelper;
document.querySelector('#helper-continue').onclick=continueHelper;
update();

let wizardStep=1;
let maxWizardStep=1;
const wizardLabels=['','Lanjut ke identitas rilis','Lanjut ke metadata lagu','Lanjut ke distributor','Selesai — ekspor paket'];
function showWizard(step){wizardStep=Math.max(1,Math.min(4,step));document.querySelectorAll('[data-wizard]').forEach(el=>el.classList.toggle('is-active',Number(el.dataset.wizard)===wizardStep));document.querySelectorAll('[data-step-indicator]').forEach(el=>{const target=Number(el.dataset.stepIndicator);el.classList.toggle('active',target===wizardStep);el.disabled=target>maxWizardStep;el.setAttribute('aria-current',target===wizardStep?'step':'false')});document.querySelector('#previous').hidden=wizardStep===1;const next=document.querySelector('#next');next.textContent=wizardLabels[wizardStep];next.hidden=wizardStep===4;window.scrollTo({top:0,behavior:'smooth'});}
document.querySelector('#next').onclick=()=>{if(wizardStep===1&&!release.tracks.length){folderStatus.textContent='Pilih folder dan pastikan ada audio di folder utama sebelum lanjut.';return}save();maxWizardStep=Math.max(maxWizardStep,wizardStep+1);showWizard(wizardStep+1)};
document.querySelector('#previous').onclick=()=>showWizard(wizardStep-1);
document.querySelectorAll('[data-step-indicator]').forEach(button=>button.onclick=()=>{const target=Number(button.dataset.stepIndicator);if(target<=maxWizardStep){save();showWizard(target)}});
showWizard(1);
restoreDraft();
checkHelper();
