const form=document.querySelector('#release-form'), folderInput=document.querySelector('#release-folder'), trackList=document.querySelector('#track-list'), folderStatus=document.querySelector('#folder-status'), researchStatus=document.querySelector('#research-status'), researchResults=document.querySelector('#research-results');
const trackFields=['trackTitle','songwriters','producers','pLine','cLine','isrc']; let release={tracks:[],artwork:null,selected:0};
const RESEARCH_API='https://release-pilot-research.uwaandfriends-production.workers.dev/research';
const esc=v=>String(v||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function parse(name){const s=name.replace(/\.[^.]+$/,'').replace(/^\d+[ ._-]+/,'').replace(/_/g,' ').trim(),p=s.split(/\s+-\s+/);return p.length>1?{title:p.slice(0,-1).join(' - '),artist:p.at(-1)}:{title:s,artist:''}}
function cur(){return release.tracks[release.selected]} function save(){if(typeof wizardStep!=='undefined'&&wizardStep===3)return;if(!cur())return;trackFields.forEach(k=>cur()[k]=form.elements[k].value);cur().artist=form.elements.primaryArtist.value||cur().artist}
function renderSongMetadata(){const box=document.querySelector('#song-metadata');if(!box)return;box.innerHTML=release.tracks.map((t,i)=>`<div class="song-row"><b>${i+1}</b><input data-song="${i}" data-key="trackTitle" value="${esc(t.trackTitle)}" aria-label="Judul lagu ${i+1}" /><input data-song="${i}" data-key="songwriters" value="${esc(t.songwriters)}" placeholder="Penulis lagu" aria-label="Penulis lagu ${i+1}" /><input data-song="${i}" data-key="isrc" value="${esc(t.isrc)}" placeholder="ISRC (opsional)" aria-label="ISRC ${i+1}" /></div>`).join('');box.querySelectorAll('[data-song]').forEach(input=>input.oninput=()=>{release.tracks[+input.dataset.song][input.dataset.key]=input.value;render();update()})}
function render(){trackList.innerHTML=release.tracks.map((t,i)=>`<button type="button" class="track ${i===release.selected?'selected':''} ${t.researched?'researched':''}" data-track="${i}"><span>${esc(t.trackTitle)}</span><small>${t.songwriters?`Pencipta: ${esc(t.songwriters)}`:'Pencipta: perlu riset'}</small><em>${t.researched?'✓ Diriset':'Riset'}</em></button>`).join('');trackList.hidden=!release.tracks.length;trackList.querySelectorAll('[data-track]').forEach(b=>b.onclick=()=>{save();release.selected=+b.dataset.track;load()})}
function load(){const t=cur();if(!t)return;trackFields.forEach(k=>form.elements[k].value=t[k]||'');if(!form.elements.primaryArtist.value&&t.artist)form.elements.primaryArtist.value=t.artist;if(!form.elements.title.value)form.elements.title.value=t.trackTitle;render();renderSongMetadata();update()}
function importFolder(){const fs=[...folderInput.files].filter(f=>f.webkitRelativePath.split('/').length===2),aud=fs.filter(f=>/\.(wav|flac|mp3|m4a)$/i.test(f.name)),imgs=fs.filter(f=>/\.(jpg|jpeg|png)$/i.test(f.name));release.artwork=imgs.find(f=>/^(cover|artwork|front)/i.test(f.name))||imgs[0];const y=new Date().getFullYear(),owner=form.elements.primaryArtist.value;release.tracks=aud.map(file=>{const p=parse(file.name),o=owner||p.artist;return{file,artist:p.artist,trackTitle:p.title,songwriters:'',producers:'',pLine:o?`℗ ${y} ${o}`:'',cLine:o?`© ${y} ${o}`:'',isrc:'',researched:false}});release.selected=0;folderStatus.textContent=aud.length?`${aud.length} lagu ditemukan di folder utama${release.artwork?` · cover: ${release.artwork.name}`:''}. Subfolder diabaikan.`:'Tidak ada audio di folder utama.';load()}
function candidateMarkup(result,trackIndex){const usable=result.candidates.filter(c=>c.songwriter);const sources=result.candidates.slice(0,5);return `<section class="research-track"><h3>${esc(result.title)}</h3>${usable.length?usable.map((c,i)=>`<article class="candidate"><div><strong>${esc(c.title)}</strong><p>Pencipta: ${esc(c.songwriter)}</p><a href="${esc(c.sourceUrl)}" target="_blank" rel="noreferrer">${esc(c.source)} · ${esc(c.sourceTitle)}</a></div><button type="button" data-pick="${trackIndex}" data-candidate="${i}">Pilih</button></article>`).join(''):`<p class="no-match">Belum ada nama pencipta yang dapat dibaca otomatis. Periksa sumber di bawah atau pilih status yang sesuai.</p>`}<div class="source-list">${sources.map(c=>`<a href="${esc(c.sourceUrl)}" target="_blank" rel="noreferrer">${esc(c.source)} · ${esc(c.sourceTitle)}</a>`).join('')}<a href="${esc(result.googleUrl)}" target="_blank" rel="noreferrer">Lihat hasil lengkap di Google</a></div><div class="fallback-actions"><button type="button" data-fallback="${trackIndex}" data-writer="Anonim">Tidak ditemukan — Anonim</button><button type="button" data-fallback="${trackIndex}" data-writer="Publik Domain">Publik domain</button></div></section>`}
function bindCandidates(results){researchResults.querySelectorAll('[data-pick]').forEach(button=>button.onclick=()=>{const item=results.find(r=>r.trackIndex===+button.dataset.pick),candidate=item?.candidates.filter(c=>c.songwriter)[+button.dataset.candidate];if(!item||!candidate)return;const track=release.tracks[item.trackIndex];track.trackTitle=candidate.title;track.songwriters=candidate.songwriter;track.researched=true;release.selected=item.trackIndex;render();load();researchStatus.textContent=`${track.trackTitle} diperbarui. Verifikasi lagi melalui tautan sumber sebelum distribusi.`});researchResults.querySelectorAll('[data-fallback]').forEach(button=>button.onclick=()=>{const track=release.tracks[+button.dataset.fallback];track.songwriters=button.dataset.writer;track.researched=true;release.selected=+button.dataset.fallback;render();load();researchStatus.textContent=`${track.trackTitle}: pencipta diisi ${track.songwriters}.`})}
async function research(all){save();const indexed=(all?release.tracks.map((track,trackIndex)=>({track,trackIndex})):[{track:cur(),trackIndex:release.selected}]).filter(x=>x.track);if(!indexed.length){researchStatus.textContent='Pilih folder terlebih dahulu.';return}const brief=form.elements.researchBrief.value.trim(),buttons=[document.querySelector('#research'),document.querySelector('#research-all')];buttons.forEach(b=>b.disabled=true);researchStatus.textContent=`Mencari referensi untuk ${indexed.length} lagu…`;researchResults.hidden=true;try{const results=[];for(let start=0;start<indexed.length;start+=3){const batch=indexed.slice(start,start+3);const found=await Promise.all(batch.map(async({track,trackIndex})=>{const response=await fetch(RESEARCH_API,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title:track.trackTitle,brief})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Riset gagal');return{...data,trackIndex}}));results.push(...found);researchStatus.textContent=`Riset ${Math.min(start+3,indexed.length)} dari ${indexed.length} lagu selesai…`}researchResults.innerHTML=results.map(r=>candidateMarkup(r,r.trackIndex)).join('');researchResults.hidden=false;bindCandidates(results);researchStatus.textContent=`Ditemukan referensi untuk ${results.length} lagu. Pilih kandidat pencipta lalu cek sumbernya.`}catch(error){researchStatus.textContent=`Riset belum berhasil: ${error.message}. Coba lagi beberapa saat.`}finally{buttons.forEach(b=>b.disabled=false)}}
function copyCommon(){save();const s=cur();if(!s)return;release.tracks.forEach(t=>{t.artist=form.elements.primaryArtist.value||t.artist;t.producers=s.producers;t.pLine=s.pLine;t.cLine=s.cLine});render();researchStatus.textContent='Artis, produser, dan baris hak disalin ke semua lagu.'}
function update(){const t=cur(),asset=t?.file||document.querySelector('#audio').files[0],art=release.artwork||document.querySelector('#artwork').files[0];document.querySelector('#asset-status').textContent=[asset&&`Audio: ${asset.name}`,art&&`Cover: ${art.name}`].filter(Boolean).join(' · ')||'Belum ada aset dipilih.';document.querySelector('#readiness').textContent=release.tracks.some(t=>!t.songwriters)?'Belum siap: pencipta lagu pada semua track.':'Periksa kembali sebelum ekspor.'}
form.addEventListener('input',update);folderInput.onchange=importFolder;document.querySelector('#research').onclick=()=>research(false);document.querySelector('#research-all').onclick=()=>research(true);
document.querySelector('#save').onclick=()=>localStorage.setItem('release-pilot-draft-v2',JSON.stringify({tracks:release.tracks.map(({file,...t})=>t)}));
document.querySelector('#export').onclick=()=>{save();const b=new Blob([JSON.stringify({tracks:release.tracks.map(({file,...t})=>({...t,audioFile:file.name}))},null,2)],{type:'application/json'}),a=Object.assign(document.createElement('a'),{href:URL.createObjectURL(b),download:'amuse-release-package.json'});a.click()};update();

let wizardStep=1;
const wizardLabels=['','Lanjut ke identitas rilis','Lanjut ke metadata lagu','Lanjut ke distributor','Selesai — ekspor paket'];
function showWizard(step){wizardStep=step;document.querySelectorAll('[data-wizard]').forEach(el=>el.classList.toggle('is-active',Number(el.dataset.wizard)===step));document.querySelectorAll('[data-step-indicator]').forEach(el=>el.classList.toggle('active',Number(el.dataset.stepIndicator)===step));document.querySelector('#previous').hidden=step===1;const next=document.querySelector('#next');next.textContent=wizardLabels[step];next.hidden=step===4;window.scrollTo({top:0,behavior:'smooth'});}
document.querySelector('#next').onclick=()=>{if(wizardStep===1&&!release.tracks.length){folderStatus.textContent='Pilih folder dan pastikan ada audio di folder utama sebelum lanjut.';return}save();showWizard(wizardStep+1)};
document.querySelector('#previous').onclick=()=>showWizard(wizardStep-1);
showWizard(1);
